### PR TITLE
Correct names for images

### PR DESCRIPTION
**Pull request by gela-d**
@tavriaforever

### CODE REVIEW

**Comment by gela-d** [comment]
@tavriaforever !!!

**Comment by gela-d** [comment]
@tavriaforever ping!

**Comment by tadatuta** [comment]
@gela-d you may merge it for the glory of all living beings ;)

**Comment by gela-d** [comment]
@tadatuta I'd like to show this changes to the author :)

**Comment by tavriaforever** [comment]
YOU're a girl with no patience :smile: 
me OK

**Pull request merged**
