### PR TITLE
make beauty in IE9

### PR DESCRIPTION
**Pull request by gela-d**

### CODE REVIEW

**Comment by tadatuta** [comment]
let's use mixes instead of cascade where it's reasonable

**Comment by gela-d** [comment]
> let's use mixes instead of cascade where it's reasonable

Its big issue for refactoring

**Comment by tadatuta** [comment]
ok, but let's plan such a refactoring otherwise it'll never be done.
and at least we can start using mixes in new code.

**Comment by gela-d** [comment]
I'll take this issue after mobile version.

**Pull request merged**
