### PR TITLE
fixed tags styling. BEMINFO-407

### PR DESCRIPTION
**Pull request by dab**

### CODE REVIEW

**Comment by tormozz48** [comment]
@tavriaforever Mykola, you must review this pr. This is UI fix

**Comment by tavriaforever** [comment]
We must refactor styles of the tags, but now for fix:
1) Change margin to 0 2px 4px 0
2) Align the indents (must be spaces)

**Comment by dab** [comment]
обновил

**Comment by tadatuta** [comment]
if it works fine in all browsers — :shipit:

**Comment by dab** [comment]
what means "all"?

**Comment by tadatuta** [comment]
All we support :)

**Comment by tavriaforever** [comment]
LGTM, rebase please & ping after

**Comment by dab** [comment]
ready

**Pull request merged**
