### PR TITLE
Implement redirect for urls that contains .sets or .docs parts with 301 status

### PR DESCRIPTION
**Pull request by tormozz48**
@tavriaforever 
@tadatuta 

Please review this pr

### CODE REVIEW

**Comment by tavriaforever** [comment]
@tadatuta I do not understand why we must support 2 way links ?

**Comment by tadatuta** [comment]
@tavriaforever i don't understand your question

**Comment by tormozz48** [comment]
Can I merge this pr?

**Comment by tadatuta** [comment]
lgtm

**Pull request merged**
