### PR TITLE
Delete unused configs

### PR DESCRIPTION
**Pull request by gela-d**

### CODE REVIEW

**Comment by gela-d** [comment]
@blond 
@tavriaforever

**Comment by tavriaforever** [comment]
Branch `leveldb` now not to start, why would you need here to update this package?

**Comment by gela-d** [comment]
@tavriaforever we use this branch in our sites

**Comment by gela-d** [comment]
@tavriaforever @tormozz48 update pr

**Comment by tavriaforever** [comment]
ok

**Pull request merged**
